{% set name = "vaex-core" %}
{% set version = "4.0.1" %}
{% set sha256 = "327da2367f3c2ce5f66e55e2daf4a66ffba4688e24d2bcfb2eb83059f78d7a06" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win and py27]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - vaex = vaex.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy
    - pip
    - pcre
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - aplus
    - tabulate >=0.8.3
    - futures >=2.2.0  # [py27]
    - future >=0.15.2
    - pyyaml
    - progressbar2
    - psutil >=1.2.1
    - requests
    - six
    - cloudpickle
    - pandas
    - dask
    - nest-asyncio >=1.3.3
    - pyarrow >=3.0
    - frozendict

test:
  imports:
    - vaex
    - vaex.vaexfast
    - vaex.core

about:
  home: https://www.github.com/vaexio/vaex
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Core of vaex
  doc_url: http://vaex.io/docs/
  dev_url: https://www.github.com/vaexio/vaex

extra:
  recipe-maintainers:
    - maartenbreddels
