travis:
  secure:
    BINSTAR_TOKEN: NL5rwVdL5YqXycXYx54N7MGEN+MrAwjwJq3YJt0HvR4iEwLlJ/BBGin8zvIoMFDnGK2lU1wenEavSOMw67Eobe4ItUP2oLBTcE/0K6wA2nHVh1RaAdpuuLreO+Gly2YRrjZsb/3OsX7D3YiD7V3gCeEKbcETBfaWo5EqSGZXj3vCGXbC6vNrW40LGbnGgcKrTQnhKnSM/SzUc/Bcqtu3pT4xiXSsov9xFBgk11FCzoMFNjef1J1UOVRJoa2Uk8T/Tuni7pvRCnxqmXs5xqALn5PtjtCZ3UrM5nLkLfITTVNTzpyYbaa/Pi48pB9VMvpTD6XSXW0a2WxX9n4NuWMgCpIdvM7iieJTKRV2GHBHCMFv8hxer7NRZGvIPzVWxIlhnGFNAhQdraA2E5HQxyO+PLrVYFvmZZk0NvIt9NmdDrMKU3mrjxefXTdcVln5ETpClbjzEngKG9CYUteo4aKt1Eag1jhOQN9Q+RZqT/VdscEJ0fCeNmqfVAd+r+jjGtx/srOZ/h4tGqfOwKm223lVOgQoCx4rfAVAZEmi+RFyS2giVikU0rXIiNIK3MmUHNmcBohax4/gJD/dh5PSAu1X2bfSCDngcgXpFlIen+b6T3ox7/CWEeOaAwKNosysL63oAePrrCSMsqBByGHML4d5EJOzW/liM8z3FjWkgLna3ho=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
