travis:
  secure:
    BINSTAR_TOKEN: LaB1v8LWWF5yeeHj9ZYw2l81NupJKGXFM8OovM0JuQIAMI2x+jGmRhiRb1V3+NwiM4P7r+5YR+8hWebN2htioij/9SjOT0ftNU/HnRlzyXUqdwXDXdXsUIKDveGPtKviMz1ES0D65uWRxiBVN9RVhtvmJjWM4MNuppSt1+mzkTc9NJKVRXFXqyKpihg1w+qSgYcJasm0St04H5JUBlk9kAKITFR3Ce7pSPcSX6RPLzOcIQzEwO8wIEuU/qLzohlSpI4Nk05mAx01sgTcItYiXmyjg1V/cdTTt0RoHkX/+yuKYfj7mOcefB4a1QSiZEBDQJo0b7Ph6PWKLWxCJAf+Yan3Ju63ggTSkvJh5yWRjVp00wggVD6Q4PxyK7wR7KyL1Jhe19lqLLuCxlHpGXdpn6Pd2et2Yy1Lo9wBLumKzi6MEY8sf2EcQYPm2KUolzM4/RCEBqf0L9/GsKlRhQzciZEbGJ6mgN/hleGCguRwwVDafdA5VjERusZSXzsBeGSupzFt44XGlnAS/wCSlP60YUsQ/sH4xHwb6RGgKJyUXLx/AL+VnhbpF73MXUYgW+BA23JNEX/+TenU5ljpWscBxl2h9H6fGfGGZqRsauccNHSfWID9s2ua8cgbSr9QpxlK6PDz698s50kHbr4ZozlRjj74uTTC8gk2fUFnjh/LCHQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
